spring:
  application:
    name: user

  datasource:
    url: jdbc:mysql://localhost:3307/your_database_name
    username: your_user
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  expiration: 360000000

server:
  port: 8081


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost