spring:
  application:
    name: api-gateway
  # cloud:
  #   gateway:
  #     mvc:
  #       routes:
  #         - id: user-service
  #           uri: http://localhost:8081
  #           predicates:
  #             - Path=/api/auth/**
          
  #         - id: product-service
  #           uri: http://localhost:8082
  #           predicates:
  #             - Path=/api/product/**

  #         - id: cart-service
  #           uri: http://localhost:8084 
  #           predicates:
  #             - Path=/api/cart/**
        

server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost

jwt:
  secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  expiration: 360000




